name: Clean Spring Boot CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - fresh-ci

jobs:
  clean-build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
      PROJECT_JWT_KEY: ${{ secrets.PROJECT_JWT_KEY }}
      PROJECT_DB_USERNAME: ${{ secrets.PROJECT_DB_USERNAME }}
      PROJECT_DB_PASSWORD: ${{ secrets.PROJECT_DB_PASSWORD }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Test
        run: |
          cd Projecta-Backend
          mvn clean test -Dspring.profiles.active=test
