name: Spring Boot CI

on:
  pull_request:
    branches:
      - main  # Ensure this runs on PRs targeting the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # AdoptOpenJDK
          java-version: '21'      # Change this to your Java version

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Run Tests
        run: |
          cd Projecta-Backend  # Navigate to project folder
          mvn test
        